### ISSUE TITLE
Release for Angular 9 support

### ISSUE THREAD

**Issue by ascandal** [rodgc/ngx-socket-io#54]
I would like to use this package with Angular 9.
Last commit e39df3e5fb48969ae7b5be2ae620749e41c84287 adds Angular 9 support.

Can we make a new 3.0.2 release?

When trying to source the master branch directly in package.json
`"ngx-socket-io": "rodgc/ngx-socket-io#master",`

I get an error when running jest test `npm run test`

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/ascandaliato/divergent3d/design-optimization-app/node_modules/ngx-socket-io/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { SocketIoModule }    from './src/socket-io.module';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      1 | import { Injectable } from '@angular/core';
    > 2 | import { Socket } from 'ngx-socket-io';
        | ^
```

**Comment by ascandal** [comment]
In the meantime adding `transform` and `transformIgnorePatterns` to jest.config.js allows to avoid the failed test suite.

```
    transform: {
        '^.+\\.(ts|js|html)$': 'ts-jest',
    },
    transformIgnorePatterns: [
        '/node_modules/(?!ngx-socket-io/).+\\.js$'
    ]
```

**Comment by ascandal** [comment]
There is another issue while running **ng serve**

```
ERROR in ./node_modules/ngx-socket-io/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/ascandaliato/divergent3d/design-optimization-app/node_modules/ngx-socket-io/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/ascandaliato/divergent3d/design-optimization-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:933:23)
    at /Users/ascandaliato/divergent3d/design-optimization-app/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Need to manually add to **tsconfig.json**

```
    "include": [
        "../common/**/*.d.ts",
        "../node_modules/ngx-socket-io/**/*"
    ],
```

**Comment by fmgrafikdesign** [comment]
I get the same error, where do I need to add this? Neither adding it to my project tsconfig.json nor to the ngx-socket-io tsconfig.json fixed the issue.

**Comment by rodgc** [comment]
This issue has been fixed on v3.2.0

**Comment by QuentinFarizon** [comment]
Is it ? I've switched to 3.2.0 and it still doesn't compile if I remove the include line tsconfig.app.json

**Comment by ascandal** [comment]
@rodgc  Awesome thank you. At this time i still see that latest tagged release is v3.0.1. I'll what for a tagged release for v3.2.0 and test.
